spring:
  config:
    import: "optional:file:./.env[.properties]"

application:
  presence:
    touch-throttle-seconds: 30     
    online-window-minutes: 5  

  login:
    attempts:
      threshold: 3         
    block:
      expiry-minutes: 20         
    password:
      placeholder: "[PROTECTED]"

  otp:
    expiry-minutes: 2    

  remember-me:
    expiry-seconds: 1209600  

  time:
    zone: "Asia/Baku"
    date-time-format: "dd-MM-yyyy HH:mm:ss"